### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by r-lyeh** [sgorsten/editor#2]
Hello world\n,

What is the license for the whole repo?
The docking support and the ability to pull panels out of the window app is impressive :)
Congrats!

**Comment by sgorsten** [comment]
Thank you for your kind words. I've pushed a commit placing everything I
came up with in that repository under the terms of the Unlicense, which
effectively makes it public domain software. Feel free to make use of
anything that is helpful to you for any purpose you deem fit. I apologize
in advance for any cruft or poor design decisions in the repository.

**Comment by r-lyeh-archived** [comment]
Hey fantastic news. Thanks for the unrestrictive license.
I will try to make something good from this :)
